### PR TITLE
corrección para ser mas comprensible

### PR DESCRIPTION
**Pull request by danielagarcia1105**
me parece que de esta forma el texto es mas claro

### CODE REVIEW

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by v-radelg** [comment]
Hola @danielagarcia1105 , le agradecemos sus comentarios y sugerencias.   	  	
Las sugerencias se combinarán con la producción y volveremos a publicar estos artículos en la siguiente versión localizada.   	  
Equipo de localización de C y E de Microsoft

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Pull request merged**
